/** Armas estilo CS — dano, cadência, precisão e queda por distância */

export const WEAPONS = {
  ak47: {
    id: "ak47",
    name: "AK-47",
    slot: 1,
    damage: 36,
    headMult: 2.5,
    fireRate: 100,
    mag: 30,
    reserve: 90,
    maxTotal: 120,
    spread: 0.022,
    adsSpread: 0.006,
    adsFov: 50,
    canADS: true,
    auto: true,
    rangeStart: 18,
    falloff: 0.012,
    pellets: 1,
    melee: false,
  },
  m4: {
    id: "m4",
    name: "M4A1",
    slot: 1,
    damage: 28,
    headMult: 2.35,
    fireRate: 86,
    mag: 30,
    reserve: 90,
    maxTotal: 120,
    spread: 0.016,
    adsSpread: 0.004,
    adsFov: 46,
    canADS: true,
    auto: true,
    rangeStart: 20,
    falloff: 0.011,
    pellets: 1,
    melee: false,
  },
  ump45: {
    id: "ump45",
    name: "UMP-45",
    slot: 1,
    damage: 24,
    headMult: 2.1,
    fireRate: 72,
    mag: 25,
    reserve: 75,
    maxTotal: 100,
    spread: 0.026,
    adsSpread: 0.01,
    adsFov: 52,
    canADS: true,
    auto: true,
    rangeStart: 12,
    falloff: 0.024,
    pellets: 1,
    melee: false,
  },
  scar: {
    id: "scar",
    name: "SCAR-H",
    slot: 1,
    damage: 31,
    headMult: 2.4,
    fireRate: 96,
    mag: 25,
    reserve: 75,
    maxTotal: 100,
    spread: 0.018,
    adsSpread: 0.005,
    adsFov: 48,
    canADS: true,
    auto: true,
    rangeStart: 22,
    falloff: 0.01,
    pellets: 1,
    melee: false,
  },
  awm: {
    id: "awm",
    name: "AWM",
    slot: 1,
    damage: 112,
    headMult: 3.2,
    fireRate: 1100,
    mag: 5,
    reserve: 20,
    maxTotal: 25,
    spread: 0.004,
    adsSpread: 0.0008,
    adsFov: 22,
    canADS: true,
    auto: false,
    rangeStart: 60,
    falloff: 0.002,
    pellets: 1,
    melee: false,
  },
  doze: {
    id: "doze",
    name: "Doze (Escopeta)",
    slot: 1,
    damage: 22,
    headMult: 2,
    fireRate: 880,
    mag: 8,
    reserve: 24,
    maxTotal: 32,
    spread: 0.07,
    auto: false,
    rangeStart: 8,
    falloff: 0.08,
    pellets: 8,
    melee: false,
  },
  bazooka: {
    id: "bazooka",
    name: "Bazuca Mítica",
    slot: 1,
    damage: 155,
    headMult: 1,
    fireRate: 1400,
    mag: 1,
    reserve: 5,
    maxTotal: 6,
    spread: 0.012,
    adsSpread: 0.004,
    adsFov: 44,
    canADS: true,
    auto: false,
    rangeStart: 18,
    falloff: 0.004,
    pellets: 1,
    explosive: true,
    melee: false,
  },
  glock: {
    id: "glock",
    name: "Glock",
    slot: 2,
    damage: 22,
    headMult: 2.2,
    fireRate: 180,
    mag: 20,
    reserve: 60,
    maxTotal: 80,
    spread: 0.028,
    auto: false,
    rangeStart: 14,
    falloff: 0.018,
    pellets: 1,
    melee: false,
  },
  revolver: {
    id: "revolver",
    name: "Revólver Frontier",
    slot: 2,
    damage: 48,
    headMult: 2.45,
    fireRate: 420,
    mag: 6,
    reserve: 36,
    maxTotal: 42,
    spread: 0.018,
    adsSpread: 0.007,
    adsFov: 48,
    canADS: true,
    auto: false,
    rangeStart: 28,
    falloff: 0.014,
    pellets: 1,
    melee: false,
  },
  faca: {
    id: "faca",
    name: "Faca",
    slot: 3,
    damage: 65,
    headMult: 1,
    fireRate: 450,
    mag: 1,
    reserve: 0,
    spread: 0,
    auto: false,
    pellets: 1,
    melee: true,
    meleeRange: 2.8,
  },
  facao: {
    id: "facao",
    name: "Facão",
    slot: 3,
    damage: 88,
    headMult: 1.1,
    fireRate: 520,
    mag: 1,
    reserve: 0,
    spread: 0,
    auto: false,
    pellets: 1,
    melee: true,
    meleeRange: 3.0,
  },
  porrete: {
    id: "porrete",
    name: "Porrete",
    slot: 3,
    damage: 105,
    headMult: 1,
    fireRate: 680,
    mag: 1,
    reserve: 0,
    spread: 0,
    auto: false,
    pellets: 1,
    melee: true,
    meleeRange: 2.6,
  },
  katana: {
    id: "katana",
    name: "Katana",
    slot: 3,
    damage: 95,
    headMult: 1.25,
    fireRate: 380,
    mag: 1,
    reserve: 0,
    spread: 0,
    auto: false,
    pellets: 1,
    melee: true,
    meleeRange: 3.2,
  },
};

export function calcWeaponDamage(weapon, distance, headshot) {
  let dmg = weapon.damage;
  if (headshot) dmg *= weapon.headMult || 2.2;
  const start = weapon.rangeStart ?? 20;
  const fall = weapon.falloff ?? 0.015;
  const mult = Math.max(0.35, 1 - Math.max(0, distance - start) * fall);
  return dmg * mult;
}

export function getPrimaryWeapon(id) {
  return WEAPONS[id] || WEAPONS.ak47;
}

/** Máximo de balas (pente + reserva) — ex: AK = 120 */
export function getWeaponMaxTotal(weaponDef) {
  if (!weaponDef || weaponDef.melee) return 0;
  return weaponDef.maxTotal ?? weaponDef.mag + weaponDef.reserve;
}

/** Enche até o máximo — descarta munição atual */
export function refillWeaponToMax(runtimeWeapon, weaponDef) {
  if (!runtimeWeapon || !weaponDef || weaponDef.melee) return;
  const max = getWeaponMaxTotal(weaponDef);
  runtimeWeapon.mag = weaponDef.mag;
  runtimeWeapon.reserve = Math.max(0, max - weaponDef.mag);
}
